environment:
  P: "c:/projects/libs"
  ACCOUNT:
      secure: F8Xu4syZJRRLmTnPDOUjr5bG7Lk6UburldIUuxZ/OJQ=
  githubtk:
      secure: qrVq5CxwKaOg2SohTmLQL6H6llxcxg1IJbF4r7Cx0Q7xxOsCPc49l2DzmlQIkui8

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\sqlite

platform: x64
configuration: Release

build_script:
  - echo Running cmake...
  - cd c:\projects\sqlite
  - cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=%P%
  - cmake --build . --target INSTALL --config Release
  - cd %P%
  - 7z a c:\projects\sqlite\sqlite.zip * -tzip
  - cd c:\projects\sqlite

artifacts:
  - path: sqlite.zip
    name: sqlite.zip

#@deploy_script:
#  - cd c:\projects\sqlite
#  - curl -T sqlite.zip --user %ACCOUNT% https://webdav.yandex.ru/libs/sqlite.zip

deploy:
  release: sqlite-v$(appveyor_build_version)
  description: 'Automatic release by Appveyor.com'
  provider: GitHub
  auth_token:
    secure: qrVq5CxwKaOg2SohTmLQL6H6llxcxg1IJbF4r7Cx0Q7xxOsCPc49l2DzmlQIkui8
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
